apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ template "logdna.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "logdna.name" . }}
    helm.sh/chart: {{ template "logdna.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 300
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                  - amd64
                  - ppc64le
                  - s390x
      containers:
      - name: kubectl
        image: "ibmcom/kubectl:v1.12.4"
        command:
        - "/bin/sh"
        - -c
        - |
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ .Release.Name }}-{{ template "logdna.name" . }}
            labels:
              app.kubernetes.io/name: {{ template "logdna.name" . }}
              helm.sh/chart: {{ template "logdna.chart" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
              release: {{ .Release.Name }}
              app.kubernetes.io/managed-by: helm
          type: Opaque
          data:
            logdna-agent-key: {{ default "" .Values.logdna.key | b64enc | quote }}
          EOF
      restartPolicy: Never